### ISSUE TITLE
some question about clustering

### ISSUE THREAD

**Issue by xuebaliang** [LuyiTian/sc_mixology#14]
hello, I am using your data for clustering experiments recently. But I found that when I use the ARI or NMI as my clustering evaluation index, the value of they can all achieve more than 0.9 for many existing methods, such as CIDR, SIMLR, RaceID and so on. Whether do you meet this phenomenon before? Thus, Is it due to the high quality of dataset so that the cell groups can be clearly distinguish? It seems the traditional Kmeans clustering method also can give perfect performance. I want to listen to your opinions. Thanks!

**Comment by LuyiTian** [comment]
It depends on which benchmark dataset you used. These cell lines have distinct gene expression patterns, so the single cell data can be easily clustered. This is why we have the mixture dataset, where the difference between clusters are more subtle. Also keep in mind that these dataset provide a baseline for method evaluation, which means having good performance on these dataset does not guarantee the similar performance on other more complicated data. If you want to challege your clustering methods, you can look at scRNAseq data from cells in differenciation, such as hematopietic stem cells (https://www.nature.com/articles/s41467-019-10291-0) or iPSCs (https://doi.org/10.1016/j.cell.2019.01.006). The different between different cell type/state will be more subtle, but the annotation will not be as good as our controlled experiment, due to the limited knowledge of the biological systems.

**Comment by qianchenxi1109** [comment]
Hi, I am experimenting with your test data as well. (Nice paper by the way, very comprehensive comparisons). However, I am having difficulties finding out the "true label" for cellmix data. 

I understand that for CellLine scRNAseq data you used "cell_line_demuxlet" as your true label, and for RNAmix data you used "mix" column to store the true label info,  but for cellmix data there is no such  group info in "colData". 

It will be great if you can help me with this issue. A bunch of thanks in advance.

**Comment by LuyiTian** [comment]
> Hi, I am experimenting with your test data as well. (Nice paper by the way, very comprehensive comparisons). However, I am having difficulties finding out the "true label" for cellmix data.
> 
> I understand that for CellLine scRNAseq data you used "cell_line_demuxlet" as your true label, and for RNAmix data you used "mix" column to store the true label info, but for cellmix data there is no such group info in "colData".
> 
> It will be great if you can help me with this issue. A bunch of thanks in advance.

Yes I agree it is not very clear. The true label are the combinations of cell numbers from three cell lines, so is the RNA mixtures. but in RNA mixtures it is the combinations of RNA proportions not cell numbers. I will update the documentation.

**Comment by sgmccalla** [comment]
Hi @LuyiTian I am curious about the true labels as well. Which file(s) contains the true cluster labels? Thanks in advance.

**Comment by LuyiTian** [comment]
@sgmccalla  I have updated the document. please check recent commit https://github.com/LuyiTian/sc_mixology/commit/bba1c35b1412aee8779bee318d454fdb7e134daa.
