### ISSUE TITLE
can't reproduce the results in the paper

### ISSUE THREAD

**Issue by klovbe** [LuyiTian/sc_mixology#19]
I want to test my imputation method following the pipeline in you nm paper. So I ran the code on RNAmix data. I first ran the script norm_impu_RNAmix.Rmd to get the data normalized and imputed. Then I ran the code blocks about RNAmix data in norm_eval.R to reproduce the plots. However, I got results totally different from figure2 and supp figure4. I changed nothing in your data and code. Could you please help me figure out what happened? Thanks a lot.

**Comment by LuyiTian** [comment]
What is the version of the softwares you used? I wont be surprised if they are different because methods changing fast in the single cell world. For example, the scran have changed their default normalization pipeline (https://osca.bioconductor.org/normalization.html#normalization-by-deconvolution), Seurat now recommand using `SCtransform` for normalization. I would recommand you read the most recent workflow for each method and rewrite the benchmark pipeline, instead of using my code, which is outdated for many methods. 
I have the R data objects after normalization and imputation, and I am happy to upload the data if you want to double check. They will be big though (~10Gb).
